### PR TITLE
1234567: Better welcome message

### PR DESCRIPTION
**Pull request by AlekseiEfimov**
Add better welcoming message.

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [JDK-1234567](https://bugs.openjdk.java.net/browse/JDK-1234567): Date objects do not preserve milliseconds properly ⚠️ Title mismatch between PR and JBS.

### Reviewers
 * Rahul Yadav ([ryadav](@rhyadav) - Author)

### Download
`$ git fetch https://git.openjdk.java.net/playground pull/28/head:pull/28`
`$ git checkout pull/28`

### CODE REVIEW

**Review by FrauBoes — COMMENTED** [review]
LGTM :)

**Comment by AlekseiEfimov** [comment]
Thanks for the review @FrauBoes :)

**Review by rhyadav — APPROVED** [review]
Looks Good

**Pull request closed without merging**
